image: node:latest


cache:
  paths:
  - node_modules/

stages:
  - pages
  - test 
  
before_script:   
  - cd website   
  - npm install
  
pages:
  script:
    - npm install
    - ./node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  only:
    - master
test:     
  stage: test     
  script:         
    - npm install
    - npm run test