image: node:latest


cache:
  paths:
  - node_modules/

stages:
  - test
  - deploy 
  

test:     
  stage: test     
  script:
    - npm install
    - npm run test

pages:
  stage: deploy
  script:
    - cd website
    - npm install
    - npm run build
    - cd ..
    - mkdir public
    - mv website/build/test-site/* public
  artifacts:
    paths:
      - public
  only:
    - master
